name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        echo 'Building'
  deploy-dev:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'DEV'
      url: 'https://dev.financials.cropwise.com/'

    steps:
    - name: deploy
      run: |
        echo 'Deploying'
  deploy-qa:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'QA'
      url: 'https://dev.financials.cropwise.com/'

    steps:
    - name: deploy
      run: |
        echo 'Deploying'
        
  deploy-staging:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: deploy-qa
    environment:
      name: 'Staging'
      url: 'https://dev.financials.cropwise.com/'

    steps:
    - name: deploy
      run: |
        echo 'Deploying'
  deploy-production:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: 'Production'
      url: 'https://dev.financials.cropwise.com/'

    steps:
    - name: deploy
      run: |
        echo 'Deploying'
